### ISSUE TITLE
Jcenter is closed

### ISSUE THREAD

**Issue by paulocoutinhox** [cioccarellia/kite#10]
Hi,

Jcenter is closed.

Can you publish it in other place?

```
implementation "com.cioccarellia:kite:1.2.0"
```

```
Could not find com.cioccarellia:kite:1.2.0.
```

Thanks.

**Comment by paulo-coutinho** [comment]
Today im using temporary:

```
implementation "com.github.cioccarellia:kite:master-SNAPSHOT"
```

**Comment by cioccarellia** [comment]
Kite is actually hosted on Maven Central since 4 months, it somehow has not occurred to me to update my publishing id and instead kept the old one. Fixing now

**Comment by cioccarellia** [comment]
Nope, readme checks out, you somehow messed up the dependency.
What's shown in the readme works.

```diff
dependencies {
-    implementation "com.cioccarellia:kite:1.2.0"
+    implementation "com.github.cioccarellia:kite:1.2.0"
}
```

**Comment by cioccarellia** [comment]
I just flashed for a moment here because if you were actually right that meant I had spend 5 hours swapping off kite from jcenter to maven and not cared spending 5 seconds adding a `.github` coordinate suffix to the readme, which sounded extra stupid even for me.

**Comment by paulo-coutinho** [comment]
Hi,

No problem man.

Thanks.
