### ISSUE TITLE
Android Resource extensions

### ISSUE THREAD

**Issue by kibotu** [cioccarellia/kite#8]
Glad I'm not the only one being tired of passing through context all day. Please have a look at https://github.com/kibotu/AndroidResourceExtensions it solves the issue of having to update context yourself and also will resolve using only application context to interact with resources which will give you unthemed values and of course won't accidently leak context as well.

Have a nice day 😊👌

**Comment by cioccarellia** [comment]
Nice day to you :)
Kite aims at being a little more compact than your implementation of extension functions over R, in the sense that it provides unified and universal access to every part of the AAPT-generated contents, from a single entry point. Namely `Kite`. To each its own I guess.
